language: go

go:
  - 1.13.x
  - 1.14.x
  - master

os:
  - linux

go_import_path: github.com/uhonliu/go-utils

env:
  - GO111MODULE=on

services:
  - mysql
  - postgresql
  - redis

before_script:
  - sudo mysql -e "USE mysql;UPDATE user SET authentication_string=password('password') WHERE user='root';FLUSH PRIVILEGES;"

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
